"""
Cryptographic utility module for the Fair Digital Dice Commitment Scheme.
Handles nonce generation, SHA256 hashing, and commitment verification.
"""

import hashlib
import secrets

def generate_cryptographic_nonce(length: int = 32) -> str:
    """
    Generates a cryptographically secure random string (nonce).
    
    This function utilizes the `secrets` module, which is designed for 
    managing secrets and is cryptographically strong, unlike the standard `random` module.
    
    Args:
        length (int): The length of the generated hex string. Defaults to 32.
        
    Returns:
        str: A secure random hexadecimal string.
    """
    # secrets.token_hex returns a string with 2 hex digits per byte, 
    # so we divide the requested length by 2.
    return secrets.token_hex(length // 2)

def calculate_commitment_hash(client_roll: int, client_nonce: str, server_nonce: str) -> str:
    """
    Calculates the SHA256 commitment hash based on the protocol specifications.
    
    The cryptographic hash is generated using the formula:
    $h_{commit} = \text{SHA256}(V_A \parallel r_A \parallel r_B)$
    where $V_A$ is the client's roll, $r_A$ is the client's nonce, and $r_B$ is the server's nonce.
    
    Args:
        client_roll (int): The integer value of the dice roll (1-6).
        client_nonce (str): The random string generated by the client ($r_A$).
        server_nonce (str): The random string generated by the server ($r_B$).
        
    Returns:
        str: The resulting SHA256 hash in hexadecimal format.
    """
    # Concatenate the payload string
    payload = f"{client_roll}{client_nonce}{server_nonce}"
    
    # Encode the string to bytes and generate the SHA256 digest
    hash_object = hashlib.sha256(payload.encode('utf-8'))
    return hash_object.hexdigest()

def verify_commitment(expected_hash: str, client_roll: int, client_nonce: str, server_nonce: str) -> bool:
    """
    Verifies the integrity of the client's commitment during the Open Phase.
    
    Args:
        expected_hash (str): The hash previously submitted by the client during the Commit Phase.
        client_roll (int): The revealed dice roll from the client.
        client_nonce (str): The revealed nonce from the client.
        server_nonce (str): The server's nonce from the current session.
        
    Returns:
        bool: True if the calculated hash matches the expected hash, False otherwise.
    """
    calculated_hash = calculate_commitment_hash(client_roll, client_nonce, server_nonce)
    return secrets.compare_digest(expected_hash, calculated_hash)